POST Http://localhost:3001/notas/nota
Content-Type: application/json

{
    "content": "tavito esta probando esto y vamos poco a poco",
    "important": true
}

###
POST Http://localhost:3001/notas/nota
Content-Type: application/json

{
    "important": true
}